export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const SET_EDIT_CURRENT_ITEM = 'SET_EDIT_CURRENT_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHANGE_SEARCH_INPUT  = 'CHANGE_SEARCH_INPUT';

export default {
  ADD_ITEM,
  EDIT_ITEM,
  SET_EDIT_CURRENT_ITEM,
  REMOVE_ITEM,
  CHANGE_SEARCH_INPUT
};